#!/usr/bin/env bash
set -e
#force a failure if there's no tag
git describe --abbrev=0
#now get the tag
CURRENT_TAG_VERSION=$(git describe --abbrev=0)
if pip install -vvv awsiotsdk==$CURRENT_TAG_VERSION; then
    echo "$CURRENT_TAG_VERSION is already in pypi, cut a new tag if you want to upload another version."
    exit 1
fi

echo "$CURRENT_TAG_VERSION currently does not exist in pypi, allowing pipeline to continue."
exit 0
