# recipe reference: https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html
---
RecipeFormatVersion: "2020-01-25"
ComponentName: com.example.greengrass_ipc.python.shadows
ComponentVersion: "1.0.0"
ComponentDescription: Greengrass IPC SDK component example
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.ShadowManager:
    VersionRequirement: ">=2.3"
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      # see https://docs.aws.amazon.com/greengrass/v2/developerguide/shadow-manager-component.html
      aws.greengrass.ShadowManager:
        com.example.greengrass_ipc.python.shadows:shadow:1:
          policyDescription: Allows access to shadows
          operations:
            - aws.greengrass#ListNamedShadowsForThing
            - aws.greengrass#GetThingShadow
            - aws.greengrass#UpdateThingShadow
            - aws.greengrass#DeleteThingShadow
          resources:
            - "*" # CHANGE ME: scope down based on principle of least privilege
      # see https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-local-shadows.html
      aws.greengrass.ipc.pubsub:
        com.example.greengrass_ipc.python.shadows:pubsub:1:
          policyDescription: Allows access to shadow sub topics
          operations:
            - aws.greengrass#SubscribeToTopic
          resources:
            - "*" # CHANGE ME: scope down based on principle of least privilege
    # see https://docs.aws.amazon.com/greengrass/v2/developerguide/shadow-manager-component.html#shadow-manager-component-configuration

Manifests:
  - Platform:
      os: linux
    Lifecycle:
      Install:
        RequiresPrivilege: true
        Script: |
          apt-get update
          apt-get install --yes python3 python3-pip
          python3 -m pip install "awsiotsdk>=1.15.0"
      Run: |
        python3 -u {artifacts:path}/code.py
